chat/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name="index"),
    path("chat/<str:room_name>/", views.room, name="room"),
    path('login/', LoginView.as_view(template_name='chat/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

djangochannelsProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat'))
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User as UserModel


class ChatModel(models.Model):
    room_name = models.CharField(max_length=100)
    members = models.ManyToManyField(UserModel, null=True, blank=True)

    def __str__(self):
        return self.room_name


class MessageModel(models.Model):
    auther = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    content = models.TextField()
    chat = models.ForeignKey(ChatModel, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date']

    @property
    def auther_username(self):
        return self.auther.username

    def __str__(self):
        return f'{self.auther}: {self.content[:20]} at {self.date}'

chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import ChatModel


@login_required(login_url='login/')
def index(request):
    chat_rooms = ChatModel.objects.filter(members=request.user)
    return render(request, "chat/index.html", {"chat_rooms": chat_rooms})


@login_required(login_url='login/')
def room(request, room_name):
    chat = ChatModel.objects.filter(room_name=room_name)
    if chat.exists():
        chat[0].members.add(request.user)
    else:
        new_chat = ChatModel.objects.create(room_name=room_name)
        new_chat.members.add(request.user)

    context = {
        "room_name": room_name,
    }
    return render(request, "chat/room.html", context)

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
{% if request.user.is_authenticated %}
    <form method="post" action="{% url 'chat:logout' %}">
        {% csrf_token %}
        <button type="submit">logout</button>
    </form>
{% endif %}<br><br>
What chat room would you like to enter?<br><br>
{% for chat_room in chat_rooms %}
    <a href="{% url 'chat:room' chat_room.room_name %}">{{ chat_room.room_name }}</a><br>
{% endfor %}
<input id="room-name-input" type="text" size="100"><br><br>
<input id="room-name-submit" type="button" value="Enter">

<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function (e) {
        if (e.key === 'Enter') {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function (e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script>
</body>
</html>

chat/templates/chat/login.html
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

chat/templates/chat/room.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
{% if request.user.is_authenticated %}
    <form method="post" action="{% url 'chat:logout' %}">
        {% csrf_token %}
        <button type="submit">logout</button>
    </form>
{% endif %}<br><br>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">
{{ room_name|json_script:"room-name" }}
{{ request.user.id |json_script:"user_id" }}
<script src="{% static 'reconnecting-websocket.js' %}"></script>
<script>
    const roomName = JSON.parse(document.getElementById('room-name').textContent);
    const user_id = JSON.parse(document.getElementById('user_id').textContent);

    const chatSocket = new ReconnectingWebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );

    chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        document.querySelector('#chat-log').value += (data.auther + ": " + data.message + '\n');
        var textarea = document.getElementById("chat-log");
        textarea.scrollTop = textarea.scrollHeight;
    };

    chatSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
        document.querySelector('#chat-log').value = '';

    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.key === 'Enter') {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function (e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'user_id': user_id

        }));
        messageInputDom.value = '';
    };
</script>
</body>
</html>